app:
  name: 'Qubity'
database:
  cluster: qubity.cqczg
  database: qubity
  username: player
  password: sgU7tWLCvPs9AO5z
  collections:
    score: score
defaultLanguage: 'en'
debugMode: false
levels: 30
locales: ['en', 'gr']
music: false
quiz:
  maxScoreHistory: 30
  revealAnswers: true
tutorialLevelId: 0
