app:
  name: 'Qubity'
debugMode: false
music: false
attributions:
  app_icon: '<a href="https://www.freepik.com/search">Icon by Freepik</a>'
  spaceships:
    - '<a href="https://www.freepik.com/search">Icon by photo3idea_studio</a>'
    - <a href="https://www.freepik.com/search">Icon by Futuer</a>
    - <a href="https://www.freepik.com/search">Icon by rsetiawan</a>
    - <a href="https://www.freepik.com/search">Icon by Freepik</a>
    - <a href="https://www.freepik.com/search">Icon by Freepik</a>
    - <a href="https://www.freepik.com/search">Icon by JK-Icon</a>
    - <a href="https://www.freepik.com/search">Icon by Freepik</a>
    - <a href="https://www.freepik.com/search">Icon by Kise1ki</a>
    - <a href="https://www.freepik.com/search">Icon by Skyclick</a>
    - <a href="https://www.freepik.com/search#uuid=2c2324dc-799e-4b03-9191-249edade3ad1">Icon by Freepik</a>
    - <a href="https://www.freepik.com/search#uuid=2c2324dc-799e-4b03-9191-249edade3ad1">Icon by Becris</a>
    - <a href="https://www.freepik.com/search#uuid=2c2324dc-799e-4b03-9191-249edade3ad1">Icon by Becris</a>
    - <a href="https://www.freepik.com/search#uuid=2c2324dc-799e-4b03-9191-249edade3ad1">Icon by Becris</a>
  enemies:
    - <a href="https://www.freepik.com/search#uuid=e19288e2-c926-4363-a009-cd2beb004a3b">Icon by msidiqf</a>
    - <a href="https://www.freepik.com/search#uuid=e19288e2-c926-4363-a009-cd2beb004a3b">Icon by IconMarketPK</a>
    - <a href="https://www.freepik.com/search#uuid=e19288e2-c926-4363-a009-cd2beb004a3b">Icon by Freepik</a>
  gates:
    - <a href="https://www.freepik.com/author/mdtanvirulhaq/icons/generic-black-fill_2005#from_element=families">Icon by Md Tanvirul Haque</a> # H
    - <a href="https://www.freepik.com/search">Icon by Md Tanvirul Haque</a> # X
    - <a href="https://www.freepik.com/search">Icon by Md Tanvirul Haque</a> # Y
    - <a href="https://www.freepik.com/search">Icon by Md Tanvirul Haque</a> # Z
    - <a href="https://www.freepik.com/icon/letter-i_14027520#fromView=families&page=1&position=1&uuid=7865aca9-0aee-44bb-8baf-21f3d2a11e26">Icon by Md Tanvirul Haque</a> # I
  others:
    - <a href="https://www.freepik.com/icon/add-button_15600739#fromView=search&page=1&position=0&uuid=92569c4d-8fce-4af7-8278-524be093eb87">Icon by Dmytro Vyshnevskyi</a> # Add