app:
  name: 'Qubity'
debugMode: false
music: false
attributions:
  icons:
    - '<a href="https://www.freepik.com/search">Icon by photo3idea_studio</a>'
    - <a href="https://www.freepik.com/search">Icon by Futuer</a>
    - <a href="https://www.freepik.com/search">Icon by rsetiawan</a>
    - <a href="https://www.freepik.com/search">Icon by Freepik</a>
    - <a href="https://www.freepik.com/search">Icon by Freepik</a>
    - <a href="https://www.freepik.com/search">Icon by JK-Icon</a>
    - <a href="https://www.freepik.com/search">Icon by Freepik</a>
    - <a href="https://www.freepik.com/search">Icon by Kise1ki</a>
    - <a href="https://www.freepik.com/search">Icon by Skyclick</a>
    - <a href="https://www.freepik.com/search#uuid=2c2324dc-799e-4b03-9191-249edade3ad1">Icon by Freepik</a>
    - <a href="https://www.freepik.com/search#uuid=2c2324dc-799e-4b03-9191-249edade3ad1">Icon by Becris</a>
    - <a href="https://www.freepik.com/search#uuid=2c2324dc-799e-4b03-9191-249edade3ad1">Icon by Becris</a>
    - <a href="https://www.freepik.com/search#uuid=2c2324dc-799e-4b03-9191-249edade3ad1">Icon by Becris</a>
