app:
  name: 'Qubity'
debugMode: false
music: false
attributions:
  app_icon: '<a href="https://www.freepik.com/search">Icon by Freepik</a>'
  spaceships:
    - '<a href="https://www.freepik.com/search">Icon by photo3idea_studio</a>'
    - <a href="https://www.freepik.com/search">Icon by Futuer</a>
    - <a href="https://www.freepik.com/search">Icon by rsetiawan</a>
    - <a href="https://www.freepik.com/search">Icon by Freepik</a>
    - <a href="https://www.freepik.com/search">Icon by Freepik</a>
    - <a href="https://www.freepik.com/search">Icon by JK-Icon</a>
    - <a href="https://www.freepik.com/search">Icon by Freepik</a>
    - <a href="https://www.freepik.com/search">Icon by Kise1ki</a>
    - <a href="https://www.freepik.com/search">Icon by Skyclick</a>
    - <a href="https://www.freepik.com/search#uuid=2c2324dc-799e-4b03-9191-249edade3ad1">Icon by Freepik</a>
    - <a href="https://www.freepik.com/search#uuid=2c2324dc-799e-4b03-9191-249edade3ad1">Icon by Becris</a>
    - <a href="https://www.freepik.com/search#uuid=2c2324dc-799e-4b03-9191-249edade3ad1">Icon by Becris</a>
    - <a href="https://www.freepik.com/search#uuid=2c2324dc-799e-4b03-9191-249edade3ad1">Icon by Becris</a>
  enemies:
    - <a href="https://www.freepik.com/search#uuid=e19288e2-c926-4363-a009-cd2beb004a3b">Icon by msidiqf</a>
    - <a href="https://www.freepik.com/search#uuid=e19288e2-c926-4363-a009-cd2beb004a3b">Icon by IconMarketPK</a>
    - <a href="https://www.freepik.com/search#uuid=e19288e2-c926-4363-a009-cd2beb004a3b">Icon by Freepik</a>
