name: qubity
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  flame: ^1.18.0
  flame_audio: ^2.10.4
  flame_noise: ^0.3.2+1
  flutter:
    sdk: flutter
  function_tree: ^0.9.1
  google_fonts: ^6.2.1
  qartvm: ^0.0.5
  shared_preferences: ^2.3.3
  yaml: ^3.1.2

dev_dependencies:
  flutter_app_name: ^0.1.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_app_name:
  name: "Qubity"

flutter:
  uses-material-design: true

  assets:
    # directories
    - assets/audio/
    - assets/google_fonts/
    - assets/images/
    - assets/images/asteroids/
    - assets/images/background/
    - assets/images/gates/
    - assets/images/icons/
    - assets/images/parallax/
    - assets/images/spaceships/
    # files
    - assets/config/config.yml
    - assets/levels/levels.yml
    - assets/levels/level_gates.yml
    - assets/levels/level_states.yml
