name: qubity
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  flame: ^1.18.0
  flame_audio: ^2.10.4
  flame_noise: ^0.3.2+1
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.3
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/images/spaceships/
    - assets/images/parallax/
    - assets/config/config.yml
    - assets/levels/levels.yml
    - assets/levels/level_gates.yml
    - assets/levels/level_states.yml
